### ISSUE TITLE
sidebar with options with multi level from json object

### ISSUE THREAD

**Issue by prashantnirgun** [mayank091193/quasar-admin-crm#1]
Hi Mayank i just saw your admin panel is incredible let me say its good work you are doing for the community. I have a feature request for you. As in real life we have options to show or hide depending upon user permission. So can we create the side bar based on Json file with multi level sub options. I try to build but its very ugly. 

If I visited to Pune will definitely call you. Are connected with Pune Vue.js Community ? 

file menu.json
`{
  "label": "Navigation",
  "level": 0,
  "children": [
    {
      "label": "Dashboard",
      "icon": "home",
      "to": "/dashboard",
      "level": 1
    },
    {
      "label": "Product Management",
      "icon": "menu_book",
      "level": 0.5,
      "children": [
        {
          "label": "Category",
          "icon": "category",
          "to": "/category",
          "level": 5
        },
        {
          "label": "Product",
          "icon": "redeem",
          "to": "/product",
          "level": 1
        },
        {
          "label": "Unit",
          "icon": "straighten",
          "to": "/unit",
          "level": 1
        },`

**Comment by mayank091193** [comment]
Hi @prashantnirgun, yes, I can build this feature. I am not sure which Pune Vue.js Community you are talking about. But I am mostly active on GitHub, Twitter, Quasar Forum, Discord, and other social networking sites. You may contact over email for further discussion. Of course, you can post here as well if you want.

**Comment by prashantnirgun** [comment]
https://www.meetup.com/VueJS-Pune I travel from Mumbai to Pune I almost
attended 4 meetups. If you are interested plz join.

**Comment by mayank091193** [comment]
Joined. I'm waiting for some supporters (Through GitHub Sponsors Program) to add more features. I'm looking forward to work on the feature you have requested.

**Comment by prashantnirgun** [comment]
let me draft you my requirement I didn't read the Sponsorship Program let
me read it I will revert back to you.

**Comment by mayank091193** [comment]
Sure. No issues. Draft me your requirement and we can discuss further.

**Comment by mayank091193** [comment]
@prashantnirgun I'm working on the feature you requested. Kindly let me know if you have already figured it out. Let me know if you have any specific requirements.

**Comment by mayank091193** [comment]
I'm closing it due to inactivity.

**Comment by prashantnirgun** [comment]
Sorry Mayank I was stuck for keeping follow up of one family member who's death by covid has not time to keep its followup. Just mark it open here 
01 Side bar has many levels of dropdown
02 Menu has around 25 root level options so margin between two options should be optional
03 Vertical option to scroll bar
04 Option to set Icon, route, Extended and collapsed Icon
05 By default Extends All, Collapsed All or Collapse particular 
06 Two variant 01 Side bar Hide completely 02 Side Bar Hide Icon only 
07 Mark Active Option
08 Options to set Background Image or Colour options as for heavy application image will be extra payload.
09 Meta Tag AuthRequired 
10 Favourite menu / Recent Opened  / Windows Pinned Application 

I few required backend functionality but that can be done by hard coding json file. I was working on two other application. was busy but surely help in what ever manner. Let me know I am working on e-commerce site. currently I am planning to use front-end site of https://github.com/mayur091193/quasar-shopping I am seeking the help of him also.

I am build a backend nodejs + mysql ORM which is a json based just like your sequelize. Sequelize is too big for small and mid size of project I am going to make  it open source I not yet implemented the sanitation that is pending with me.  My mail id is prashant[dot]nirgun[dot]gmail[dot]com
