### ISSUE TITLE
Dark mode doesn't change main page background colour

### ISSUE THREAD

**Issue by TonyMasse** [mayank091193/quasar-admin-crm#18]
**Describe the bug**
When switching to Dark mode, the background of the page stays white.

**To Reproduce**
1. Click on the Dark/Light mode icon to switch to Dark mode

**Expected behavior**
Dark mode should change the page background too

**Screenshots**
(see red arrows)

![image](https://user-images.githubusercontent.com/50835088/137506182-1071f34e-f1da-43b4-9a44-6eb361a80663.png)

![image](https://user-images.githubusercontent.com/50835088/137506316-664649c2-323d-426c-be6d-32739b95f5cf.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Chrome 94.0.4606.81 (Official Build) (64-bit)

**Additional context**
None.

**Comment by mayank091193** [comment]
This is not a bug. I have kept it as it is for now. If required, the user can easily change it.
